apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exporter
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: node-exporter
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-exporter
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
      - hostPath:
        path: /sys
        name: sys
      - hostPath:
        path: /
        name: root
      containers:
        - name: node-exporter
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          args:
            - --path.sysfs=/host/sys
            - --path.rootfs=/host/root
          ports:
            - name: http
              containerPort: 9100
              protocol: TCP
          volumeMounts:
          - mountPath: /host/sys
            mountPropagation: HostToContainer
            name: sys
            readOnly: true
          - mountPath: /host/root
            mountPropagation: HostToContainer
            name: root
            readOnly: true
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
