

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.


apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  labels:
    name: prometheus
data:
  prometheus.yml: |-
    global:
      scrape_interval: 30s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
      evaluation_interval: 30s # Evaluate rules every 15 seconds. The default is every 1 minute.
    scrape_configs:
    - job_name: "chargino"
      static_configs:
      - targets: ["192.168.1.1:9090"]